global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'spring-microsservicos'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['usuarios:9001', 'tarefas:9001']