spring.application.name=lista-de-tarefas-usuarios

spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME_USUARIOS:usuarios_db}

spring.datasource.username=${DB_USER:lista}
spring.datasource.password=${DB_PASSWORD:lista123}

api.security.token.secret=${JWT_SECRET:listadetarefas2026listadetarefas2026listadetarefas2026}

spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:update}

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

